### ISSUE TITLE
One question.

### ISSUE THREAD

**Issue by Ivan-Sandro** [techiew/Misc-Projects#1]
I saw your program "3DOpenGL", and I asked myself "Why so many .h files?" one file for each .cpp file, I understand that .h files are good for declarations and making one file for each cpp you were dividing the program, but ... there are so many files that literally duplicated your code, I saw in your code two equals "#include", if I'm not mistaken is <iostream>, this absurd amount of difficulty even when it comes to reading a code that was supposed to be simpler ... so ... why did you prefer use this method?

(PS:My English is not perfect, please ignore it or say if something is wrong.)

**Comment by techiew** [comment]
I agree that there are an unecessary amount of files and that they decrease the readability of the code. Having tons of files is a horrible experience for everyone. 

It seems this is a common problem when people write C++ code, because people are taught from the beginning to make header files for every single class, even though it probably makes little to no difference in compilation times with small programs such as this. Despite its faults its a good pattern to practice though. 

So I didn't really choose to do it this way for any particular reason, it was a just a default path of action. As for the 3DOpenGL project, I probably could have merged some of my classes into fewer files, since some of them are very short.

**Comment by Ivan-Sandro** [comment]
I see, it really is a good practice, and sometimes we do it even without wanting to, but sometimes weighing whether it is worth it or not to put this good practice on is good, in fact for the program there is no difference that is worth being mentioned, after all, there are compilers to take care of this, but for the readability of the code ... it didn't help much, and you can see it just because of the repetition of "#include", but that was all I had to say, thanks To answer.

**Comment by Ivan-Sandro** [comment]
Thinking about this subject made me study a little more about Listeners and Sourcers, I intend to even put them in a project still under development by me, and really the number of files and the repetition of #includes are almost inevitable in this type of arrangement, it was good to review this topic, but it really makes it difficult to read the code IF you don't write it properly, normally people use quotes ("//" or "/ * * /") in the Headers, we all know the "advantages and disadvantages "of this, explaining each command in more detail, finally, thanks for responding.
